In [13]:
# Importing packages
import numpy as np
# import matplotlib as plt
import pandas as pd

In [14]:
# Loading dataset
df = pd.read_csv(r'C:\Users\Lenovo\Desktop\my_random_projects\Perceptron\Single Layer Perceptron Dataset.csv')
df

    Pattern  Feature1  Feature2  Feature3  Class_Label
0       1.0       1.0      0.08      0.72          1.0
1       2.0       1.0      0.10      1.00          1.0
2       3.0       1.0      0.26      0.58          1.0
3       4.0       1.0      0.35      0.95          0.0
4       5.0       1.0      0.45      0.15          1.0
5       6.0       1.0      0.60      0.30          1.0
6       7.0       1.0      0.70      0.65          0.0
7       8.0       1.0      0.92      0.45          0.0
8       9.0       1.0      0.42      0.85          0.0
9      10.0       1.0      0.65      0.55          0.0
10     11.0       1.0      0.20      0.30          1.0
11     12.0       1.0      0.20      1.00          0.0
12     13.0       1.0      0.85      0.10          1.0
13      NaN       NaN       NaN       NaN          NaN

In [15]:
df.dropna(inplace=True)

### Summation and bias

In [16]:
# initializing the w vector and bias
w = np.random.randn(3) * 0.01 
b = 0.01
z = np.dot(x,w) + b
z

array([0.05460798, 0.03924354, 0.02586997, 0.03036433, 0.03309678,
       0.05210447, 0.04892906, 0.03628216, 0.05540432, 0.04313468,
       0.03447544, 0.04823326, 0.04146334])

### Applying activation function

In [17]:
y_pred = [1 if val >= 0 else 0 for val in z]

In [18]:
df['Predicted'] = y_pred
df

    Pattern  Feature1  Feature2  Feature3  Class_Label  Predicted
0       1.0       1.0      0.08      0.72          1.0          1
1       2.0       1.0      0.10      1.00          1.0          1
2       3.0       1.0      0.26      0.58          1.0          1
3       4.0       1.0      0.35      0.95          0.0          1
4       5.0       1.0      0.45      0.15          1.0          1
5       6.0       1.0      0.60      0.30          1.0          1
6       7.0       1.0      0.70      0.65          0.0          1
7       8.0       1.0      0.92      0.45          0.0          1
8       9.0       1.0      0.42      0.85          0.0          1
9      10.0       1.0      0.65      0.55          0.0          1
10     11.0       1.0      0.20      0.30          1.0          1
11     12.0       1.0      0.20      1.00          0.0          1
12     13.0       1.0      0.85      0.10          1.0          1

In [19]:
learning_rate = 0.1
epoch_count = 100
errors_log = []

for i in range(epoch_count):
    errors = 0
    # Shuffle data in each epoch for better learning
    df = df.sample(frac=1).reset_index(drop=True)

    # Extract new x and y after each epoch
    x = df[['Feature1', 'Feature2', 'Feature3']].values
    y_label = df['Class_Label'].values

    # Predict using current weights
    z = np.dot(x, w) + b
    y_pred = [1 if val >= 0 else 0 for val in z]
    df['Predicted'] = y_pred

    # Update weights if prediction is wrong
    for index, row in df.iterrows():
        x_i = row[['Feature1', 'Feature2', 'Feature3']].values
        if row['Class_Label'] != row['Predicted']:
            errors += 1
            w = w + learning_rate * (row['Class_Label'] - row['Predicted']) * x_i
            b = b + learning_rate * (row['Class_Label'] - row['Predicted'])

    # Track errors per epoch
    errors_log.append(errors)
    if errors == 0:
        break
print(errors_log)

[6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 6, 5, 6, 7, 6, 7, 6, 5, 3, 3, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]

In [20]:
# Final prediction on the full dataset
final_preds = [1 if val >= 0 else 0 for val in np.dot(x, w) + b]
accuracy = np.mean(final_preds == y_label)
print("Final Accuracy:", accuracy)
print(y_label,final_preds)

Final Accuracy: 1.0
[1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1.] [1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1]